import {IArchetype} from "../Domain/IArchetype";

export const Archetypes: IArchetype[] = [
	{ name: 'Addict', description: 'Become utterly fixated on one passion.' },
	{ name: 'Adherent', description: 'Pledge yourself to one cause above everything else.' },
	{ name: 'Adjudicator', description: 'Work to solve problems that affect your surroundings.' },
	{ name: 'Alpha', description: 'Lead other by example.' },
	{ name: 'Architect', description: 'Strive to create something out of a sense of greater purpose. Your strength is Purpose, while your weakness is Obsession.' },
	{ name: 'Artiste', description: 'Try to reach others through your creations.' },
	{ name: 'Autocrat', description: 'Seek power and prominence for its own sake. Your strength is Leadership and your weakness is Dictatorship.' },
	{ name: 'Barbarian', description: 'Keep your distance from civilization, instead trusting the old ways.' },
	{ name: 'Benefactor', description: 'Work to protect the people around you. Your strength is Altruism, while your weakness is Obligation.' },
	{ name: 'Beta', description: 'Act as supporter for your group’s superior.' },
	{ name: 'Bon Vivant', description: 'Try to enjoy life as long as it lasts. Your strength is your Love of Life, while your weakness is Hedonism.' },
	{ name: 'Bravo', description: 'Use your power to bully others into submission. Your strength is Strength, while your weakness is Anger.' },
	{ name: 'Capitalist', description: 'Strive to make profit by selling your commodities.' },
	{ name: 'Caregiver', description: 'Take comfort in consoling others. Your strength is Compassion, while your weakness comes from Smothering.' },
	{ name: 'Caretaker', description: 'Shepherd the flock around you to safety. Your strength is a Sense of Duty, while your weakness is Impatience.' },
	{ name: 'Celebrant', description: 'Take great joy out of your passion. Your strength is Passion, while your weakness is Intemperance.' },
	{ name: 'Chameleon', description: 'Constantly alter your mannerisms and appearance.' },
	{ name: 'Child', description: 'Be ignorant about the larger world around you. Your strength is Innocence, while your weakness is Immaturity.' },
	{ name: 'Competitor', description: 'Put yourself against the world’s odds. Your strength is Striving, while your weakness is Competitiveness.' },
	{ name: 'Conformist', description: 'Play your strengths in groups. Your strength is cooperation, while your weakness is Low Self-Esteem.' },
	{ name: 'Conniver', description: 'Seek ways to let others work for you. Your strength is Cleverness, while your weakness is Envy.' },
	{ name: 'Coward', description: 'Hide your true self from all others.' },
	{ name: 'Creep Show', description: 'Strive to inspire shock and disgust for show.' },
	{ name: 'Crusader', description: 'Fight for an ideal of yours. Your strength is Zeal, while your weakness is Fanaticism.' },
	{ name: 'Curmudgeon', description: 'Constantly expect the worst to happen. Your strength is your Critical Eye, while your weakness is your Lack of Imagination.' },
	{ name: 'Dabbler', description: 'Seek to find new interests.' },
	{ name: 'Defender', description: 'Protect something over yourself.' },
	{ name: 'Deviant', description: 'Reject traditional social mores for your own. Your strength is your ability to Shatter Boundaries, while your weakness is Perversion.' },
	{ name: 'Devil’s Advocate', description: 'Question the commands from your superiors. Your strength is Skepticism, while your weakness is Contrariness.' },
	{ name: 'Director', description: 'Work to bring order into strife. Your strength is Organization, while your weakness is a Lack of Tolerance.' },
	{ name: 'Enigma', description: 'Work to keep your true intentions hidden.' },
	{ name: 'Eye of the Storm', description: 'Find yourself constantly in the centre of unrest.' },
	{ name: 'Explorer', description: 'Strive to discover new places and experiences.' },
	{ name: 'Fanatic', description: 'Pledge yourself to one goal over all else. Your strength is Dedication, while your weakness is Stubbornness.' },
	{ name: 'Fatalist', description: 'Follow the inescapable course of destiny.' },
	{ name: 'Futurist', description: 'Pledge yourself to new concepts and ideals.' },
	{ name: 'Gambler', description: 'Trust in luck to take care of you.' },
	{ name: 'Gallant', description: 'Seek attention and adulation from others. Your strength is Artistry, while your weakness is Flamboyance.' },
	{ name: 'Guru', description: 'Lead others to spiritual fulfillment.' },
	{ name: 'Heretic', description: 'Refuse to accept a commonly held creed. Your strength is Integrity, while your weakness is Iconoclasm.' },
	{ name: 'Hunter', description: 'Always prepare yourself for the hunt.' },
	{ name: 'Idealist', description: 'Believe into a higher ideal than yourself.' },
	{ name: 'Judge', description: 'Seek to improve the system by using rational conclusions. Your strength is Justice, your weakness your Lack of Vision.' },
	{ name: 'Loner', description: 'Keep your own company. Your strength is Self-Reliance, while your weakness is a Lack of Empathy.' },
	{ name: 'Machine', description: 'Push yourself to your limits to transcend mortal weakness. Your strength is Work Ethic, your weakness is Burn-Out.' },
	{ name: 'Maniac', description: 'Be compelled by internal voices to strange actions.' },
	{ name: 'Martyr', description: 'Sacrifice yourself for your cause. Your strength is Sacrifice, your weakness is Self-Deprecation.' },
	{ name: 'Masochist', description: 'Draw pleasure from suffering and testing your boundaries. Your strength is Devotion, while your weakness is Self-Destructiveness.' },
	{ name: 'Masquerader', description: 'Leave no footprints to mortals.' },
	{ name: 'Meddler', description: 'Constantly try to interfere into other’s affairs to aid them.' },
	{ name: 'Melancholic', description: 'Feel ennui at all that you have lost.' },
	{ name: 'Monster', description: 'Seek to understand your own depravity by acting on it. Your strength is your Mirror of Villainy, while your weakness is Depravity.' },
	{ name: 'Omega', description: 'Accept your place at the bottom rung of your group.' },
	{ name: 'Outsider', description: 'Define yourself by things you do not participate in.' },
	{ name: 'Paragon', description: 'Embody straightforwardness and simplicity in your actions.' },
	{ name: 'Pedagogue', description: 'Share your knowledge with those around you. Your strength is Knowledge, your weakness is Logorrhea.' },
	{ name: 'Penitent', description: 'Strive to do penance for your sins. Your strength is Responsibility, while your weakness is Contrition.' },
	{ name: 'Perfectionist', description: 'Work to achieve the best result possible. Your strength is Exactitude, while your weakness is Incompleteness.' },
	{ name: 'Quaestor', description: 'Yearn to answer life’s questions.' },
	{ name: 'Rebel', description: 'Fight against established authorities. Your strength is Individuality, while your weakness is your Lack of Direction.' },
	{ name: 'Recognition Seeker', description: 'You want to be recognized.' },
	{ name: 'Reluctant Reborn', description: 'You have a hard time accepting your new life. Your moods often swing between denial and depression.' },
	{ name: 'Rogue', description: 'Focus on your own gain over that of others. Your strength is Valor, while your weakness is Selfishness.' },
	{ name: 'Sadist', description: 'Inflict pain and misery on others.' },
	{ name: 'Scientist', description: 'Work to achieve understanding of your surroundings via a critical method.' },
	{ name: 'Seer', description: 'Glimpses of the future haunt you.' },
	{ name: 'Sociopath', description: 'Strive to eradicate weakness.' },
	{ name: 'Soldier', description: 'Work within the chain of command to fulfill your duties.' },
	{ name: 'Stoic', description: 'Maintain your composure under all circumstances.' },
	{ name: 'Survivor', description: 'Strive to survive all odds. Your strength is Perseverance, while your weakness is a Lack of Trust.' },
	{ name: 'Thrill-Seeker', description: 'Actively seek the rush of danger. Your strength is Daring, while your weakness is Recklessness.' },
	{ name: 'Traditionalist', description: 'Keep on established routines. Your strength is Consistency, while your weakness is Complacency.' },
	{ name: 'Trickster', description: 'Find humour and the absurd in all situations. Your strength is Empathy, your weakness is Hypocrisy.' },
	{ name: 'Tycoon', description: 'Constantly plot to expand your resources. Your strength is Savviness, while your weakness is Greed.' },
	{ name: 'Vigilante', description: 'Succeed in your vengeance against a chosen target. Your strength is Single-Mindedness, your weakness is Blood-Blindness.' },
	{ name: 'Visionary', description: 'See beyond the mundane to focus on what things should be. Your strength is Imagination, your weakness is Pride.' },
	{ name: 'Wanderer', description: 'Never stay in one place and never form attachments.' },
];
